export const typesActions = {
    // Users
    START_GETTING_USERS: "START_GETTING_USERS",
    SUCCESS_GETTING_USERS: "SUCCESS_GETTING_USERS",
    ERROR_GETTING_USERS: "ERROR_GETTING_USERS",

    // Roles
    START_GETTING_ROLES: "START_GETTING_ROLES",
    SUCCESS_GETTING_ROLES: "SUCCESS_GETTING_ROLES",
    ERROR_GETTING_ROLES: "ERROR_GETTING_ROLES",

    // Permissions
    START_GETTING_PERMISSIONS: "START_GETTING_PERMISSIONS",
    SUCCESS_GETTING_PERMISSIONS: "SUCCESS_GETTING_PERMISSIONS",
    ERROR_GETTING_PERMISSIONS: "ERROR_GETTING_PERMISSIONS"
};
